#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: create file systems
  filesystem: fstype={{ item.fstype }}  dev={{ item.device }}
  with_items: "{{ nfs_exports }}"

- name: assure exports directories exist
  file:
    dest: "{{ item.mount_point }}"
    owner: root
    group: root
    state: directory
    recurse: yes
    mode: 0775
  with_items: "{{ nfs_exports }}"

- name: mount the storage on the export directories
  mount:
    name: "{{ item.mount_point }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.mount_opts }}"
    state: mounted
  with_items: "{{ nfs_exports }}"

- name: generate exports file
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
  notify:
    - nfs reexport
