#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: Upgrade apt cache
  apt: update_cache=yes

- name: assure nfs packages and kernel modules installed
  apt: pkg={{ item }} state=installed
  with_items:
    - nfs-kernel-server

- name: turn off NFSv4 security
  lineinfile:
    dest: "/etc/default/nfs-kernel-server"
    regexp: "^NEED_SVCGSSD="
    line: "NEED_SVCGSSD=no"
    state: present
