#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: install deps
  yum: name={{ item }} state=latest
  with_items:
    - nfs-utils
  notify:
    - restart nfs-kernel-server
