#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: restart nfs-kernel-server
  service: name=nfs-server state=restarted

- name: nfs reexport
  command: "exportfs -ra"
